version: '3.9'
services:
	backend:
		build: ./backend
		ports:
			- "8000:8000"
		environment:
			- APP_ENV=production
			- YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
			- LINKEDIN_API_KEY=${LINKEDIN_API_KEY}
		restart: unless-stopped

	frontend:
		build: ./frontend
		ports:
			- "5173:80"
		depends_on:
			- backend
		restart: unless-stopped


